Browser 111.0
mozilla-japan/gecko-l10n pull request #374
Opened 2023-02-20 11:39 UTC by marsf

2023-02-21 18:46 UTC, hokonch commented on ja/toolkit/toolkit/about/aboutGlean.ftl
> +    あなたの実装した手動テストを動作させるには、以下を行ってください。
簡潔に述べると、インストルメンテーションが動作することを手動でテストするには、以下を行ってください。

2023-02-21 19:09 UTC, hokonch requested changes
とりあえず、`about:glean`だけ見てます。
Firefox 開発者向けの文章ですし、実際の動作を知らない翻訳者が訳しても誤訳が混じるだけだと思うんで、訳さないほうがいいくらいだと思うんですが。

`instrumentation`が実装と訳されてますが、基本的に違う概念ですし、一般ユーザ向けではないので単にカタカナ化すればいいでしょう。

2023-02-21 19:09 UTC, hokonch commented on ja/toolkit/toolkit/about/aboutGlean.ftl
> +    この <code>about:glean</code> ページで開発ツールのコンソールを開き、<code>Glean.metricCategory.metricName.testGetValue()</code> のように <code>testGetValue()</code> API を使用してください。
さらに、\<i>アドホック\</i>にテストを行うには、\<code>about:glean\</code> ページで開発ツールのコンソールを開き、\<code>Glean.metricCategory.metricName.testGetValue()\</code> などの\<code>testGetValue()\</code> API を使用して、インストルメンテーションの特定の一部について現在の値を特定することもできます。

2023-02-21 19:09 UTC, hokonch commented on ja/toolkit/toolkit/about/aboutGlean.ftl
> +    左のボタンを押してすべての { -glean-brand-name } にあたたのタグを付け、選択した Ping を送信してください。
あたた→あなた

2023-02-21 19:09 UTC, hokonch commented on ja/toolkit/toolkit/about/aboutGlean.ftl
> +about-glean-label-for-tag-pings = 左のフィールドにメモ用のデバッグタグを設定して、後であなたの Ping が区別できるようにしてください。
メモ用の→覚えやすい

2023-02-22 17:07 UTC, hokonch reviewed
誤訳ではありませんが、残りの気になったところを。

2023-02-22 17:07 UTC, hokonch commented on ja/browser/browser/protectionsPanel.ftl
> +protections-panel-cookie-banner-view-turn-on-description = サポートされたサイトで { -brand-short-name } が自動的にすべての Cookie 要求を拒否しようとします。
{ -brand-short-name } は、サポートされたサイト上のCookie 同意確認に対し自動拒否を試みます。

2023-02-27 04:16 UTC, marsf commented
@hokonch @bcolsson レビューありがとうございます。修正しました。
about:glean の instrument の訳は「計測器」にしました。

参考:
https://github.com/mozilla/glean/
https://mozilla.github.io/glean/book/appendix/twig.html

2023-02-28 06:40 UTC, hokonch requested changes
`dns-not-found-trr-only-title` → `dns-not-found-trr-only-title2` の要点はドメイン自体に問題があったわけではなく、DoHの過程で問題が生じたのだということを明確にするためなので現訳は誤訳でしょう。　https://bugzilla.mozilla.org/show_bug.cgi?id=1812028

2023-02-28 06:40 UTC, hokonch commented on ja/toolkit/toolkit/neterror/certError.ftl
> +dns-not-found-trr-only-title2 = このドメインのセキュリティ上の危険性を調べています
このドメインの検索にはセキュリティ上の危険性があります

2023-02-28 06:40 UTC, hokonch commented on ja/devtools/client/perftools.ftl
> +perftools-description-local-build = この端末で自身でビルドしたバイナリをプロファイリングする場合は、シンボル情報を利用可能にしてビルドした objdir を以下のリストに追加してください。
シンボル情報を利用可能にして → シンボル情報の検索に使用できるように

2023-03-01 11:35 UTC, marsf commented
@hokonch ありがとうございます。修正しました。

2023-03-01 11:37 UTC, merged

2023-03-01 11:53 UTC, marsf commented
https://hg.mozilla.org/l10n-central/ja/rev/ab887affb5fd22dbebca8dd71780282d7ed4e827
https://hg.mozilla.org/l10n-central/ja-JP-mac/rev/3f0b15eb476f09a539e3c44a638e724827835888